doctrine:
    dbal:
        default_connection : premiersymfo50
        connections :
            premiersymfo50:
                driver: 'pdo_mysql'
                server_version: '8.0'
                charset: utf8mb4
                default_table_options:
                        charset: utf8mb4
                        collate: utf8mb4_unicode_ci
                dbname: '%env(DATABASE_NAME)%'
                host: '%env(DATABASE_HOST)%'
                user: '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PWD)%'
            databasecreator:
                driver: 'pdo_mysql'
                server_version: '8.0'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4 unicode ci
                dbname: '%env(DATABASE_NAME)%'
                host: '%env(DATABASE_HOST)%'
                user: '%env(DATABASE_CREATOR_USER)%'
                password: '%env(DATABASE_CREATOR_PWD)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
